/**
 * Works data — single source of truth for the TOP page works grid
 * and each work's detail page (works/detail.html?work=<slug>).
 * Edit this array to add / update / remove projects.
 */
const WORKS = [
  {
    slug: 'aurora-studio',
    title: 'Aurora Studio',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Figma', 'HTML / CSS', 'JavaScript', 'GSAP'],
    url: 'https://example.com/aurora-studio',
    period: '2025.04 - 2025.06',
    summary: 'クリエイティブスタジオのブランドサイト。デザインからコーディングまで一貫して担当。',
    description: 'クリエイティブスタジオのコーポレートサイトを、デザインからフロントエンド実装まで一貫して担当しました。ブランドの世界観を伝えるため、スクロールに連動したアニメーションや繊細なタイポグラフィにこだわって制作しています。',
    thumb: 'grad-1',
    num: '01',
  },
  {
    slug: 'nozomi-dashboard',
    title: 'Nozomi Dashboard',
    category: ['frontend'],
    positions: ['Frontend'],
    tools: ['React', 'TypeScript', 'D3.js'],
    url: 'https://example.com/nozomi-dashboard',
    period: '2025.02 - 2025.03',
    summary: 'データ可視化ダッシュボードの実装。React + D3.jsでインタラクティブなUIを構築。',
    description: '社内向けのデータ可視化ダッシュボードを実装しました。React + TypeScriptで基盤を構築し、D3.jsを用いて大量のデータをインタラクティブなグラフとして表示できるようにしています。',
    thumb: 'grad-2',
    num: '02',
  },
  {
    slug: 'kioku-magazine',
    title: 'Kioku Magazine',
    category: ['design'],
    positions: ['Web Design'],
    tools: ['Figma', 'Illustrator'],
    url: 'https://example.com/kioku-magazine',
    period: '2024.11 - 2024.12',
    summary: 'Webマガジンのビジュアルデザイン。エディトリアルな余白とタイポグラフィを意識。',
    description: 'カルチャー系Webマガジンのビジュアルデザインを担当しました。紙媒体のエディトリアルデザインを参考に、余白の取り方とタイポグラフィにこだわり、読み物としての心地よさを追求しています。',
    thumb: 'grad-3',
    num: '03',
  },
  {
    slug: 'hanare-hotel',
    title: 'Hanare Hotel',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Figma', 'HTML / CSS', 'JavaScript', 'GSAP'],
    url: 'https://example.com/hanare-hotel',
    period: '2024.08 - 2024.10',
    summary: '宿泊施設のコーポレートサイト。スクロールに連動したアニメーションを実装。',
    description: '宿泊施設のコーポレートサイトを制作しました。施設の落ち着いた雰囲気を表現するため、スクロールに連動したアニメーションや余白を活かしたレイアウトを意識してデザイン・実装しています。',
    thumb: 'grad-4',
    num: '04',
  },
  {
    slug: 'playground-lab',
    title: 'Playground Lab',
    category: ['frontend'],
    positions: ['Frontend'],
    tools: ['JavaScript', 'Canvas API', 'WebGL', 'Three.js'],
    url: 'https://example.com/playground-lab',
    period: '2024.05 - 2024.06',
    summary: 'Canvas / WebGLを使った実験的なインタラクションコレクション。',
    description: 'Canvas / WebGLを用いた実験的なインタラクションを集めた個人プロジェクトです。パーティクルや3D表現など、日々のインプットをコードに落とし込みながら継続的にアップデートしています。',
    thumb: 'grad-5',
    num: '05',
  },
  {
    slug: 'marginal-coffee',
    title: 'Marginal Coffee',
    category: ['design'],
    positions: ['Web Design'],
    tools: ['Figma', 'Illustrator', 'Photoshop'],
    url: 'https://example.com/marginal-coffee',
    period: '2024.01 - 2024.03',
    summary: 'カフェブランドのロゴ・グラフィック・Webサイトのトータルデザイン。',
    description: 'カフェブランドの立ち上げに合わせて、ロゴ・グラフィックツール・Webサイトのトータルデザインを担当しました。ナチュラルで親しみやすいブランドイメージを、一貫したビジュアルで表現しています。',
    thumb: 'grad-6',
    num: '06',
  },
];
