/**
 * Works data — single source of truth for the TOP page works grid
 * and each work's detail page (works/detail.html?work=<slug>).
 * Edit this array to add / update / remove projects.
 */
const WORKS = [
  {
    slug: 'jozankei-view-hotel-sauna',
    title: '定山渓ビューホテル／サウナページ',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.jozankeiview.com/sauna/',
    period: '2024.05 - 2024.07',
    summary: '定山渓ビューホテルのサウナページ。デザインからコーディングまで一貫して担当。',
    description: '2024年7月と12月に館内施設のサウナがリニューアルするため、既存のサウナページのサイトリニューアルを行いました。2種類のコンセプトに分かれたサウナそれぞれの魅力訴求を目的としたデザインに取り組みました。',
    thumb: 'grad-1',
    num: '01',
  },
  {
    slug: 'exective-suite-suirei',
    title: 'エグゼクティブスイート翠嶺',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.jozankeiview.com/suirei/',
    period: '2024.08 - 2024.10',
    summary: '新規開業ホテルのECサイトを構築。Photoshopを使用したワイヤーフレーム作成からHTML/CSS、JSでの実装まで担当',
    description: '定山渓ビューホテル高層階に高級客室がオープン。集客を目的に公式ECサイトを作成。高級路線をコンセプトに落ち着いた雰囲気のイメージで制作。',
    thumb: 'grad-2',
    num: '02',
  },
  {
    slug: 'kyoto-granbell-hanareya',
    title: '京都グランベルホテル hanareya',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.granbellhotel.jp/kyoto/hanareya/',
    period: '2022.10 - 2022.11',
    summary: '京都の離れ家風ホテルのオープンに際しwebデザインと実装を担当。高級感かつシンプルな構成を意識。',
    description: '新規ホテルの立ち上げに伴い、公式ECサイトを制作。デザイナーズホテルのため高級感と和風の雰囲気をイメージ。',
    thumb: 'grad-3',
    num: '03',
  },
  {
    slug: 'hanare-hotel',
    title: 'Hanare Hotel',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Figma', 'HTML / CSS', 'JavaScript', 'GSAP'],
    url: 'https://example.com/hanare-hotel',
    period: '2024.08 - 2024.10',
    summary: '宿泊施設のコーポレートサイト。スクロールに連動したアニメーションを実装。',
    description: '宿泊施設のコーポレートサイトを制作しました。施設の落ち着いた雰囲気を表現するため、スクロールに連動したアニメーションや余白を活かしたレイアウトを意識してデザイン・実装しています。',
    thumb: 'grad-4',
    num: '04',
  },
  {
    slug: 'playground-lab',
    title: 'Playground Lab',
    category: ['frontend'],
    positions: ['Frontend'],
    tools: ['JavaScript', 'Canvas API', 'WebGL', 'Three.js'],
    url: 'https://example.com/playground-lab',
    period: '2024.05 - 2024.06',
    summary: 'Canvas / WebGLを使った実験的なインタラクションコレクション。',
    description: 'Canvas / WebGLを用いた実験的なインタラクションを集めた個人プロジェクトです。パーティクルや3D表現など、日々のインプットをコードに落とし込みながら継続的にアップデートしています。',
    thumb: 'grad-5',
    num: '05',
  },
  {
    slug: 'marginal-coffee',
    title: 'Marginal Coffee',
    category: ['design'],
    positions: ['Web Design'],
    tools: ['Figma', 'Illustrator', 'Photoshop'],
    url: 'https://example.com/marginal-coffee',
    period: '2024.01 - 2024.03',
    summary: 'カフェブランドのロゴ・グラフィック・Webサイトのトータルデザイン。',
    description: 'カフェブランドの立ち上げに合わせて、ロゴ・グラフィックツール・Webサイトのトータルデザインを担当しました。ナチュラルで親しみやすいブランドイメージを、一貫したビジュアルで表現しています。',
    thumb: 'grad-6',
    num: '06',
  },
];
