/**
 * Works data — single source of truth for the TOP page works grid
 * and each work's detail page (works/detail.html?work=<slug>).
 * Edit this array to add / update / remove projects.
 */
const WORKS = [
  {
    slug: 'jozankei-view-hotel-sauna',
    title: '定山渓ビューホテル／サウナページ',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.jozankeiview.com/sauna/',
    period: '2024.05 - 2024.07',
    summary: '定山渓ビューホテルのサウナページ。デザインからコーディングまで一貫して担当。',
    description: '2024年7月と12月に館内施設のサウナがリニューアルするため、既存のサウナページのサイトリニューアルを行いました。2種類のコンセプトに分かれたサウナそれぞれの魅力訴求を目的としたデザインに取り組みました。',
    thumb: 'grad-1',
    num: '01',
  },
  {
    slug: 'exective-suite-suirei',
    title: 'エグゼクティブスイート翠嶺',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.jozankeiview.com/suirei/',
    period: '2024.08 - 2024.10',
    summary: '新規開業ホテルのECサイトを構築。Photoshopを使用したワイヤーフレーム作成からHTML/CSS、JSでの実装まで担当',
    description: '定山渓ビューホテル高層階に高級客室がオープン。集客を目的に公式ECサイトを作成。高級路線をコンセプトに落ち着いた雰囲気のイメージで制作。',
    thumb: 'grad-2',
    num: '02',
  },
  {
    slug: 'kyoto-granbell-hanareya',
    title: '京都グランベルホテル hanareya',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.granbellhotel.jp/kyoto/hanareya/',
    period: '2022.10 - 2022.11',
    summary: '京都の離れ家風ホテルのオープンに際しwebデザインと実装を担当。高級感かつシンプルな構成を意識。',
    description: '新規ホテルの立ち上げに伴い、公式ECサイトを制作。デザイナーズホテルのため高級感と和風の雰囲気をイメージ。',
    thumb: 'grad-3',
    num: '03',
  },
  {
    slug: 'jozankei-view-hotel-scene',
    title: '定山渓ビューホテル／過ごし方ページ',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['Photoshop', 'HTML / CSS', 'JavaScript'],
    url: 'https://www.jozankeiview.com/scene/',
    period: '2023.11 - 2023.12',
    summary: '「家族の過ごし方」「カップルで過ごす」「女子会で楽しむ」「四季を体感する」の４つのターゲット・目的別に館内と周辺観光を合わせたおすすめの過ごし方の提案するサイトを制作。',
    description: '「家族の過ごし方」「カップルで過ごす」「女子会で楽しむ」「四季を体感する」の４つのターゲット・目的別に館内と周辺観光を合わせたおすすめの過ごし方の提案するサイトを制作。初めて定山渓で宿泊・観光する方に1泊2日で楽しめるプランを時系列ごとに紹介しています。',
    thumb: 'grad-4',
    num: '04',
  },
  {
    slug: 'portfolio',
    title: 'Tomokai Satou portfolio site',
    category: ['design', 'frontend'],
    positions: ['Web Design', 'Frontend'],
    tools: ['HTML / CSS', 'JavaScript'],
    url: 'https://tomoaki4719.github.io/tofo4714.github.io/',
    period: '2026.09',
    summary: 'Webデザインとフロントエンドのスキルを伝える、ポートフォリオサイト。。',
    description: 'Webデザイナー／フロントエンドエンジニアとしての制作実績やスキルを紹介するポートフォリオサイトを制作しました。デザインからコーディングまで一貫して担当し、シンプルなレイアウトをベースに、アニメーションやインタラクションを取り入れることで、見た目の美しさと操作する心地よさの両立を目指しています。',
    thumb: 'grad-5',
    num: '05',
  },
];
